### ISSUE TITLE
[BUG] Missing 'util' module

### ISSUE THREAD

**Issue by bilwis** [danikhan632/guidance_api#1]
I think we're missing a file in the most recent commit.

> 2023-06-24 07:15:57 ERROR:Failed to load the extension "guidance_api".
Traceback (most recent call last):
  File "/home/bilwis/text-generation-webui/modules/extensions.py", line 34, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "/home/bilwis/text-generation-webui/extensions/guidance_api/script.py", line 11, in <module>
    from .guidance_gen import GuidanceGenerator
  File "/home/bilwis/text-generation-webui/extensions/guidance_api/guidance_gen.py", line 3, in <module>
    from .util import build_parameters
ModuleNotFoundError: No module named 'extensions.guidance_api.util'

Thank you for your work, btw, can't wait to try it out!

**Comment by danikhan632** [comment]
fixed thanks for pointing that out
