### ISSUE TITLE
Failed to load extension 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by Nixellion** [danikhan632/guidance_api#5]
```
2023-07-15 22:07:19 ERROR:Failed to load the extension "guidance_api".
Traceback (most recent call last):
  File "O:\Workspace\AI\LLM\ooba\text_generation_webui_01\text-generation-webui\modules\extensions.py", line 41, in load_extensions
    extension.setup()
  File "O:\Workspace\AI\LLM\ooba\text_generation_webui_01\text-generation-webui\extensions\guidance_api\script.py", line 134, in setup
    gen =GuidanceGenerator()
  File "O:\Workspace\AI\LLM\ooba\text_generation_webui_01\text-generation-webui\extensions\guidance_api\guidance_gen.py", line 36, in __init__
    self.data= setup_model_data()
  File "O:\Workspace\AI\LLM\ooba\text_generation_webui_01\text-generation-webui\extensions\guidance_api\model_info.py", line 71, in setup_model_data
    if "falcon" in shared.args.model.lower():
AttributeError: 'NoneType' object has no attribute 'lower'
```

I don't use falcon, so I just commented that whole block out and it launched after that (and after installing extra requirements manually which are mentioned in another issue)

**Comment by danikhan632** [comment]
Going to update today, been a bit disappointed that Microsoft has updated repo in a while. Hopefully happens soon, either way I'll update today.
